# Generated by Django 3.1.7 on 2021-03-07 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movie_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movie_photo', models.CharField(max_length=300, unique=True)),
                ('movie_video', models.CharField(max_length=300, unique=True)),
                ('movie_photo_actual', models.ImageField(blank=True, upload_to='')),
                ('movie_video_actual', models.FileField(blank=True, upload_to='')),
                ('genre', models.ManyToManyField(to='first_app.Genre')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
