# Generated by Django 3.1.7 on 2021-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_movies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_video',
            field=models.FileField(upload_to=''),
        ),
    ]
